Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (90, null, 'Alimentos');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (91, null, 'Eletrônicos');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (92, null, 'Industrializados');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (93, null, 'Medicamentos e Higiene Pessoal');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (94, null, 'Diversos');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (001, 90, 'SECOS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (002, 92, 'PRODUTOS TRANSFORMADOS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (003, 90, 'BEBIDAS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (004, 92, 'PRODUTOS INDUSTRIALIZADOS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (005, 93, 'PERFUMARIA E LIMPEZA');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (006, 93, 'DROGARIA');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (007, 94, 'MATERIAIS P/CONSUMO');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (008, 91, 'ELETRO');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (009, 90, 'ACOUGUE');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (010, 94, 'BAZAR II');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (011, 94, 'OUTRAS RECEITAS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (013, 90, 'PADARIA');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (014, 94, 'F.L.V.');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (015, 94, 'EVENTOS');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (017, 94, 'BAZAR I');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (018, 92, 'TEXTIL');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (019, 90, 'PEIXARIA');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (020, 90, 'LANCHONETE');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (030, 94, 'Animais e Vegetais');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (031, 94, 'Produtos Autmobilisticos');


Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (032, 94, 'Casa e Jardinagem');

Insert into GRUPO_DE_PRODUTOS
       (NUMERO_DO_GRUPO_DE_PRODUTO,SUP_NUMERO_DO_GRUPO_DE_PRODUTO, NOME_DO_GRUPO_DE_PRODUTO)
Values (033, 94, 'Importados');
go
